const words = {
	'das Abgas': 'spaliny✅',
	'das Abwasser': 'ścieki✅',
	'das Aussterben': 'wymieranie',
	'die Bedrohung': 'zagrożenie✅',
	belasten: 'obciążać, zanieczyszczać',
	'das Bewusstsein': 'świadomość',
	'der Bio-Müll': 'odpady biodegradowalne',
	'die CO2-Emission': 'emisja dwutlenku węgla',
	'die Dürre': 'susza✅',
	'der Einfluss auf': 'wpływ na',
	'sich einsetzen für': 'angażować się za, wstawiać się za',
	'die Energiesparlampe': 'żarówka energooszczędna',
	'sich engagieren für': 'angażować się na rzecz',
	'die Entscheidung': 'decyzja',
	'die Erdoberfläche': '✅powierzchnia Ziemi✅',
	erneuerbar: 'odnawialny',
	'erneuerbare Energienquelle': 'odnawialne źródła energii',
	'die Erwärmung': 'ocieplenie się',
	'die globale Erwärmung': 'globalne ocieplenie',
	'die Filteranlage': 'urządzenie filtrujące',
	'die Folge': 'skutek',
	'die Gewohnheit': 'nawyk, przyzwyczajenie',
	'die Glühbirne': 'żarówka',
	'die Heizung': 'grzejnik, kaloryfer',
	'die Industrie': 'przemysł',
	'kämpfen für, gegen': 'walczyć o, przeciw',
	'die Kläranlage': 'oczyszczalnia ścieków✅',
	'der Klimawandel': 'zmiana klimatu✅',
	'das Kunstleder': 'sztuczna skóra',
	künstlich: 'sztuczny, z tworzywa sztucznego',
	'der Kunststoff': 'tworzywo sztuczne',
	'das Licht': 'światło',
	'das Licht anlassen': 'zostawić włączone światło',
	'das Licht ausschalten': 'wyłączać światło',
	loswerden: 'pozbywać się',
	'die Luft': 'powietrze✅',
	'die Luftverschmutzung': 'zanieczyszczenie powietrza',
	'die Maßnahme': 'działanie',
	'der Müll': 'śmieci',
	'den Müll entsorgen': 'usuwać śmieci',
	'die Mülldeponie': 'wysypisko śmieci✅',
	'der Müllhaufen': 'góra śmieci',
	'die Mülltonne': 'duży pojemnik na śmieci, kubeł',
	'die Mülltrennung': 'segregacja śmieci',
	nützen: 'przynosić korzyść, przydawać się',
	öffentlich: 'publiczny',
	'öffentliche Verkehrsmittel': 'publiczne środki transportu',
	'der Ökotourismus': 'ekoturystyka, turystyka ekologiczna',
	pflanzen: 'sadzić',
	recyceln: 'poddawać recyklingowi, utylizować',
	'der Restmüll': 'pozostałe śmieci zmieszane',
	'die Rücksicht auf': 'wzgląd na',
	'Rücksicht nehmen auf': 'uwzględniać, mieć wzgląd na',
	saisonal: 'sezonowy',
	schaden: 'szkodzić',
	'der Schadstoff': 'substancja szkodliwa',
	schmelzen: 'topnieć, topić✅',
	schützen: 'chronić',
	'die Solaranlage': 'instalacja solarna',
	sortieren: 'sortować',
	sparen: 'oszczędzać',
	'das Stand-by': 'funkcja czuwania',
	'Elektrogeräte auf Stand-by lassen': 'zostawiać urządzenia elektryczne w funkcji czuwania',
	'die Stofftasche': 'torba z materiału',
	'der Straßenverkehr': 'ruch drogowy',
	'der Tierversuch': 'doświadczenie na zwierzętach',
	trennen: 'sortować',
	'die Tüte': 'torba foliowa, pot. reklamówka',
	überfüllt: 'przepełnienie✅',
	'die Umwelt': 'środowisko naturalne✅✅',
	umweltfreundlich: 'przyjazny środowisku',
	'die Umweltmaßnahme': 'działanie na rzecz środowiska',
	umweltschädlich: 'szkodliwy dla środowiska',
	'der Umweltschutz': 'ochrona środowiska',
	'die Verantwortung für': 'odpowiedzialność za',
	verantwortungsbewusst: 'odpowiedzialny',
	verbrauchen: 'zużywać',
	vergiftet: 'zatruty✅',
	verschmutzen: 'zanieczyszczać✅',
	'verzichten auf': 'rezygnować z',
	'der Wasserhahn': 'kran',
	'den Wasserhahn zudrehen': 'zakręcać kran',
	'die Windkraftanlage': 'turbina wiatrowa',
	'die Wüstenbildung': 'stawanie się pustynią, pustynnienie',
	'die Wüste': 'pustynia✅',
	verursachen: 'powodować✅',
	'der Gletscher': 'lodowiec✅',
	'die Panne': 'awaria✅',
	wegen: 'z powodu✅',
	zeigen: 'pokazać✅',
	ernsthaft: 'poważnie✅',
	einladen: 'zapraszać✅',
	'der Auftritt': 'wystąpienie✅',
	bedeuten: 'znaczyć✅',
	wählen: 'wybierać✅',
}
