const words = {
	'vending machine': 'automat (z napojami lub przekąskami)',
	'DIY store': 'sklep z artykułami do majsterkowania',
	'duty-free': 'sklep wolnocłowy',
	'go window-shopping': 'oglądać wystawy sklepowe',
	laundrette: 'pralnia samoobsługowa',
	'pop-up store': 'sklep działający w określonym sezonie',
	'retail outlet': 'punkt sprzedaży detalicznej',
	apparel: 'odzież',
	footwear: 'obuwie',
	'household chemicals': 'chemia gospodarcza',
	stationery: 'artykuły biurowe',
	'end of line': 'końcówka kolekcji',
	'fair price': 'uczciwa cena',
	'value for money': 'towar wart swojej ceny',
	affordable: 'w zasięgu możliwości finansowych',
	unaffordable: 'poza zasięgiem możliwości finansowych',
	'cheap and cheerful': 'tani, ale dobrej jakości',
	'for a song': 'tani',
	'low key': 'skromny',
	upmarket: 'z wyższej półki',
	bargain: 'okazja cenowa',
	branch: 'oddział, filia',
	charge: 'pobierać (opłatę), liczyć sobie (za coś)',
	convenient: 'wygodny, dogodny',
	'keep a receipt': 'zachować paragon',
	'put up the price': 'podwyższyć cenę',
	trolley: 'wózek sklepowy',
	aisle: 'alejka (w supermarkecie)',
	'buy in bulk': 'kupować hurtowo',
	'cost next to nothing': 'kosztować tyle, co nic',
	'meet expectations': 'spełniać oczekiwania',
	'pay in installments': 'kupić na raty',
	'pay upfront': 'płacić z góry',
	'pick up a bargain': 'znaleźć okazję',
	'put sth aside': 'odłożyć coś (w sklepie)',
	'shortage of': 'brak',
	'loose change': 'drobne',
	'flyer/leaflet': 'ulotka',
	'celebrity endorsement': 'udział znanej osoby w reklamie',
	'cold calling': 'akwizycja przez telefon',
	tailor: 'krawiec/krawcowa',
	caterer: 'osoba/firma zajmująca się kateringiem',
	'private tutor': 'korepetytor/korepetytorka',
	solicitor: 'adwokat, radca prawny',
	undertaker: 'zakład/przedsiębiorca pogrzebowy',
	refund: 'zwrot pieniędzy',
	faded: 'spłowiały',
	scratched: 'zarysowany',
	shrunk: 'skurczony',
	torn: 'rozdarty',
	'bank loan': 'kredyt w banku',
	'cash flow': 'przepływ gotówki',
	currency: 'waluta',
	'go in the red': 'być na minusie (jak Rokita)',
	overdraft: 'debet',
	'pay interest': 'płacić odsetki',
	'save money for a rainy day': 'oszczędzać na czarną godzinę',
	shareholder: 'akcjonariusz',
	'stocks and bonds': 'akcje i obligacje',
	withdraw: 'wypłacić (pieniądze z banku)',
	'fraudulent claim': 'fałszywe roszczenie',
	'make a claim': 'wystąpić o odszkodowanie',
	policyholder: 'osoba ubezpieczona',
	'cooling-off period': 'okres odstąpienia od umowy',
	'make a claim against sb': 'wystąpić z roszczeniem przeciwko komuś',
}
