const words = [
	{ english: 'apricot', polish: 'morela' },
	{ english: 'blackcurrant', polish: 'czarna porzeczka' },
	{ english: 'gooseberry', polish: 'agrest' },
	{ english: 'tangerine', polish: 'mandarynka' },
	{ english: 'aubergine', polish: 'bakłażan' },
	{ english: 'chives', polish: 'szczypiorek' },
	{ english: 'kale', polish: 'jarmuż' },
	{ english: 'leek', polish: 'por' },
	{ english: 'cod', polish: 'dorsz' },
	{ english: 'poultry', polish: 'drób' },
	{ english: 'prawn', polish: 'krewetka' },
	{ english: 'crumble', polish: 'ciasto owocowe z kruszonką' },
	{ english: 'packet of crisps', polish: 'paczkę czipsów' },
	{ english: 'jug of milk', polish: 'dzbanek mleka' },
	{ english: 'spoonful of sugar', polish: 'łyżeczka cukru' },
	{ english: 'brunch', polish: 'późne śniadanie' },
	{ english: 'grate', polish: 'zetrzeć na tarce' },
	{ english: 'sprinkle', polish: 'posypać, pokropić' },
	{ english: 'gulp', polish: 'połknąć' },
	{ english: 'rinse', polish: 'opłukać' },
	{ english: 'stew', polish: 'dusić na wolnym ogniu' },
	{ english: 'kettle', polish: 'czajnik' },
	{ english: 'crockery', polish: 'naczynia, porcelana stołowa' },
	{ english: 'cutlery', polish: 'sztućce' },
	{ english: 'sieve', polish: 'sitko' },
	{ english: 'edible', polish: 'jadalny' },
	{ english: 'inedible', polish: 'niejadalny' },
	{ english: 'mild', polish: 'łagodny' },
	{ english: 'sharp', polish: 'ostry, cierpki' },
	{ english: 'bland', polish: 'mdły' },
	{ english: 'lumpy', polish: 'grudkowaty' },
	{ english: 'off-putting', polish: 'odpychający' },
	{ english: 'revolting', polish: 'odrażający, okropny' },
	{ english: 'scrumptious', polish: 'przepyszny' },
	{ english: 'additives', polish: 'dodatki do żywności, np. barwniki' },
	{ english: 'crash diet', polish: 'intensywna dieta odchudzająca' },
	{ english: 'cut down on', polish: 'ograniczyć' },
	{ english: 'put on weight', polish: 'przytyć' },
	{ english: 'well-balanced diet', polish: 'zrównoważona dieta' },
	{ english: 'daily intake', polish: 'dzienna dawka' },
	{ english: 'high-fibre', polish: 'bogate w błonnik' },
	{ english: 'nutritious', polish: 'pożywny' },
	{ english: 'processed food', polish: 'żywność przetworzona' },
	{ english: 'saturated fats', polish: 'tłuszcze nasycone' },
	{ english: 'wholemeal', polish: 'razowy' },
	{ english: 'bill', polish: 'rachunek' },
	{ english: 'cuisine', polish: 'kuchnia, sposób gotowania' },
	{ english: 'main course', polish: 'danie główne' },
	{ english: 'review', polish: 'recenzja' },
	{ english: 'self-service', polish: 'samoobsługa, samoobsługowy' },
	{ english: 'takeaway', polish: '(danie) na wynos' },
	{ english: 'delicacies', polish: 'przysmaki, delikatesy' },
	{ english: 'side dish', polish: 'dodatek do dania głównego' },
	{ english: 'binge eating disorder', polish: 'zespół napadowego objadania się' },
	{ english: 'compulsive', polish: 'kompulsywny' },
	{ english: 'fixated on sth', polish: 'mieć obsesję na punkcie czegoś' },
	{ english: 'malnutrition', polish: 'niedożywienie' },
	{ english: 'overly concerned', polish: 'nadmiernie zaniepokojony' },
	{ english: 'restrictive eating patterns', polish: 'ograniczony schemat żywienia' },
]